package movie;
public class OTTPlatformMain {

    public static void main(String[] args) {

        separator("OTT PLATFORM — MOVIE LIBRARY SYSTEM");
        section("1. ARRAY — Movie Library (Fixed-size catalog)");

        MovieLibrary library = new MovieLibrary();
        library.addMovie(new Movie(5,  "Interstellar",           "Sci-Fi",    8.6, 980000, 2014));
        library.addMovie(new Movie(2,  "The Dark Knight",        "Action",    9.0, 1500000,2008));
        library.addMovie(new Movie(8,  "Inception",              "Sci-Fi",    8.8, 1200000,2010));
        library.addMovie(new Movie(1,  "The Shawshank Redemption","Drama",    9.3, 870000, 1994));
        library.addMovie(new Movie(7,  "Parasite",               "Thriller",  8.6, 560000, 2019));
        library.addMovie(new Movie(3,  "Avengers: Endgame",      "Action",    8.4, 2200000,2019));
        library.addMovie(new Movie(10, "Spirited Away",          "Animation", 8.6, 420000, 2001));
        library.addMovie(new Movie(4,  "The Godfather",          "Drama",     9.2, 990000, 1972));
        library.addMovie(new Movie(6,  "The Matrix",             "Sci-Fi",    8.7, 1100000,1999));
        library.addMovie(new Movie(9,  "Coco",                   "Animation", 8.4, 750000, 2017));
        library.addMovie(new Movie(11, "Mad Max: Fury Road",     "Action",    8.1, 680000, 2015));
        library.addMovie(new Movie(12, "Hereditary",             "Thriller",  7.3, 310000, 2018));

        library.displayAll();
        section("2. LINKED LIST — Recently Watched & Trending");

        MovieLinkedList recentlyWatched = new MovieLinkedList("Recently Watched");
        Movie[] movies = library.getMovies();
        recentlyWatched.insertAtHead(movies[0]);   
        recentlyWatched.insertAtHead(movies[2]);   
        recentlyWatched.insertAtHead(movies[5]);   
        recentlyWatched.display();

        System.out.println("\n  Removing 'Inception' from recently watched...");
        recentlyWatched.removeByTitle("Inception");
        recentlyWatched.display();

        System.out.println("\n  [Linked List] Trending list will be generated by RecommendationEngine.");
        section("3. STACK (LIFO) — Watch History");

        WatchHistoryStack watchHistory = new WatchHistoryStack("Alice", 5);
        watchHistory.push(movies[0]);  
        watchHistory.push(movies[3]);   
        watchHistory.push(movies[1]);   
        watchHistory.push(movies[2]);   
        watchHistory.display();

        System.out.println("\n  [Resume] Checking last watched movie:");
        watchHistory.resumeLast();

        System.out.println("\n  [Undo] User un-watches last movie:");
        watchHistory.pop();
        watchHistory.display();
        section("4. QUEUE (FIFO) — Watch-Later & Streaming");

        WatchLaterQueue watchLater    = new WatchLaterQueue("Watch Later", 10);
        WatchLaterQueue streamingQueue = new WatchLaterQueue("Streaming Requests", 5);

        watchLater.enqueue(movies[4]);    
        watchLater.enqueue(movies[6]);    
        watchLater.enqueue(movies[9]);   
        watchLater.enqueue(movies[8]);   
        watchLater.display();

        System.out.println("\n  [Watch Later] Starting next movie...");
        watchLater.dequeue();
        watchLater.display();
        System.out.println();
        streamingQueue.enqueue(movies[7]);  
        streamingQueue.enqueue(movies[11]);  
        streamingQueue.enqueue(movies[10]); 
        System.out.println("\n  [Streaming] Processing all queued requests:");
        streamingQueue.processAll();
        section("5. SEARCHING — Linear (title/genre) & Binary (by ID)");
        SearchEngine.linearSearchByTitle(library.getMovies(), library.getCount(), "Matrix");
        SearchEngine.linearSearchByTitle(library.getMovies(), library.getCount(), "Batman"); 

        SearchEngine.linearSearchByGenre(library.getMovies(), library.getCount(), "Sci-Fi");

        System.out.println();
        SearchEngine.sortByIdForBinarySearch(library.getMovies(), library.getCount());
        SearchEngine.binarySearchById(library.getMovies(), library.getCount(), 7);   
        SearchEngine.binarySearchById(library.getMovies(), library.getCount(), 99);  
        section("6. SORTING — Bubble (rating), Selection (views), Merge (title)");

        System.out.println("\n--- 6a. Bubble Sort: By Rating (descending) ---");
        SortingEngine.bubbleSortByRating(library.getMovies(), library.getCount());

        System.out.println("\n--- 6b. Selection Sort: By Popularity / Views (descending) ---");
        SortingEngine.selectionSortByViews(library.getMovies(), library.getCount());

        System.out.println("\n--- 6c. Merge Sort: Alphabetically by Title (A→Z) ---");
        SortingEngine.mergeSortByTitle(library.getMovies(), library.getCount());
        section("7. RECOMMENDATION ENGINE");

        MovieLinkedList recommended = RecommendationEngine.recommend(library, watchHistory);
        recommended.display();

        MovieLinkedList trending = RecommendationEngine.trending(library);
        trending.display();
        separator("ALL FEATURES DEMONSTRATED SUCCESSFULLY");
    }

    private static void section(String title) {
        System.out.println("\n");
        System.out.println("  " + title);
        System.out.println(" ");
    }

    private static void separator(String title) {
        System.out.println("\n");
        System.out.println("  " + title);
        System.out.println("\n");
    }
}
